# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from avsa_api.proto import avsa_pb2 as avsa__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in avsa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversationStub(object):
    """Conversation is the orchestrator's stateful entry point. A conversation is
    identified by a client-supplied UUID; the GenServer behind this service
    keeps state until the supervisor restarts it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartConversation = channel.unary_unary(
                '/avsa.orchestrator.v1.Conversation/StartConversation',
                request_serializer=avsa__pb2.StartConversationRequest.SerializeToString,
                response_deserializer=avsa__pb2.ConversationEvent.FromString,
                _registered_method=True)
        self.StreamConversationEvents = channel.unary_stream(
                '/avsa.orchestrator.v1.Conversation/StreamConversationEvents',
                request_serializer=avsa__pb2.StartConversationRequest.SerializeToString,
                response_deserializer=avsa__pb2.ConversationEvent.FromString,
                _registered_method=True)


class ConversationServicer(object):
    """Conversation is the orchestrator's stateful entry point. A conversation is
    identified by a client-supplied UUID; the GenServer behind this service
    keeps state until the supervisor restarts it.
    """

    def StartConversation(self, request, context):
        """StartConversation runs a turn to completion and returns the last
        ConversationEvent emitted. Used for batch / non-streaming callers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConversationEvents(self, request, context):
        """StreamConversationEvents runs a turn and emits every ConversationEvent
        (tool calls, product results, errors) as the orchestrator generates
        them. The gateway translates this stream into the SSE response on
        `POST /chat`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartConversation,
                    request_deserializer=avsa__pb2.StartConversationRequest.FromString,
                    response_serializer=avsa__pb2.ConversationEvent.SerializeToString,
            ),
            'StreamConversationEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConversationEvents,
                    request_deserializer=avsa__pb2.StartConversationRequest.FromString,
                    response_serializer=avsa__pb2.ConversationEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avsa.orchestrator.v1.Conversation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avsa.orchestrator.v1.Conversation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Conversation(object):
    """Conversation is the orchestrator's stateful entry point. A conversation is
    identified by a client-supplied UUID; the GenServer behind this service
    keeps state until the supervisor restarts it.
    """

    @staticmethod
    def StartConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avsa.orchestrator.v1.Conversation/StartConversation',
            avsa__pb2.StartConversationRequest.SerializeToString,
            avsa__pb2.ConversationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConversationEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avsa.orchestrator.v1.Conversation/StreamConversationEvents',
            avsa__pb2.StartConversationRequest.SerializeToString,
            avsa__pb2.ConversationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
