# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avsa.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'avsa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\navsa.proto\x12\x14\x61vsa.orchestrator.v1\"[\n\x18StartConversationRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x02 \x03(\x0c\x12\x11\n\tuser_text\x18\x03 \x01(\t\"\xda\x01\n\x11\x43onversationEvent\x12\x42\n\x0eproduct_result\x18\x02 \x01(\x0b\x32(.avsa.orchestrator.v1.ProductResultEventH\x00\x42\t\n\x07payloadJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07R\ttool_callR\x10\x61g_ui_tool_startR\x13\x61g_ui_tool_completeR\x13\x61g_ui_intent_updateR\x11\x61g_ui_layout_hint\"N\n\x12ProductResultEvent\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x15\n\rmetadata_json\x18\x03 \x01(\t2\xf3\x01\n\x0c\x43onversation\x12l\n\x11StartConversation\x12..avsa.orchestrator.v1.StartConversationRequest\x1a\'.avsa.orchestrator.v1.ConversationEvent\x12u\n\x18StreamConversationEvents\x12..avsa.orchestrator.v1.StartConversationRequest\x1a\'.avsa.orchestrator.v1.ConversationEvent0\x01\x42\x62\n\x17\x61i.avsa.orchestrator.v1ZGgithub.com/avsa/orchestrator/gen/go/avsa/orchestrator/v1;orchestratorv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avsa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.avsa.orchestrator.v1ZGgithub.com/avsa/orchestrator/gen/go/avsa/orchestrator/v1;orchestratorv1'
  _globals['_STARTCONVERSATIONREQUEST']._serialized_start=36
  _globals['_STARTCONVERSATIONREQUEST']._serialized_end=127
  _globals['_CONVERSATIONEVENT']._serialized_start=130
  _globals['_CONVERSATIONEVENT']._serialized_end=348
  _globals['_PRODUCTRESULTEVENT']._serialized_start=350
  _globals['_PRODUCTRESULTEVENT']._serialized_end=428
  _globals['_CONVERSATION']._serialized_start=431
  _globals['_CONVERSATION']._serialized_end=674
# @@protoc_insertion_point(module_scope)
