# lib/avsa/proto/*.pb.ex is generated by `buf generate` and committed verbatim
# for the proto-gen-elixir drift check (which diffs against raw buf output). It is
# intentionally NOT mix-formatted, so exclude it here — otherwise
# `mix format --check-formatted` fights the drift check.
[
  inputs:
    ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
    |> Enum.flat_map(&Path.wildcard/1)
    |> Enum.reject(&String.starts_with?(&1, "lib/avsa/proto/"))
]
