#!/usr/bin/env python3
# AVSA — catalog seeder for `catalog.products`.
#
# Data sources (selected by [catalog.source] in config/avsa.toml):
#
#   synthetic-v1 (default) — deterministic per-index synthetic products
#     generated by `machine_learning_engineering_interview.catalog_seed`.
#     No external dataset is fetched; all rows (titles, colours, prices,
#     image URLs, 768-d embeddings) are derived from a fixed-seed RNG so
#     the seed job is hermetic and reproducible. This source keeps CI and
#     the hermetic pytest fixture working.
#
#   fashion200k (opt-in) — joins the self-describing
#     manifest (--manifest) to the pre-computed embedding artifact
#     (--embedding-artifact) and loads real titles/categories, derived
#     colour/price/formality/occasion, real 768-d image + 512-d text
#     embeddings into catalog.products. The seeder does NOT call the live
#     ViT per row — embeddings come from the artifact.
#
# License: synthetic-v1 data is owned by this project (MIT, matching the
# repo). Fashion200k is research-use; its provenance/license is documented
# in STAKEHOLDERS.md. Update STAKEHOLDERS.md before changing data sources.
#
# Embedding path (synthetic-v1 only):
#   AVSA_EMBED_STUB=1 → use catalog_seed.stub_embedding (deterministic).
#   AVSA_EMBED_STUB=0 → POST each row's image_url to the ViT /embed
#                       endpoint at AVSA_EMBED_URL (default
#                       http://localhost:8001/embed) and use the returned
#                       768-d vector. The endpoint contract is owned by
#                       the model service in
#                       `machine_learning_engineering_interview.model`.
#   (The fashion200k source ignores AVSA_EMBED_STUB — its vectors come
#    pre-computed from the artifact.)
#
# Throughput: rows are written via psycopg3 ``COPY ... FROM STDIN``
# (see catalog_seed.copy_rows) — row-by-row INSERTs would be ~10x
# slower at 5000+ rows and gate the CI seed budget.

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterator

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from machine_learning_engineering_interview import catalog_seed  # noqa: E402

DEFAULT_CONFIG = REPO_ROOT / "config" / "avsa.toml"
DEFAULT_EMBED_URL = "http://localhost:8001/embed"
DEFAULT_MANIFEST = REPO_ROOT / "evals" / "catalog" / "fashion200k" / "manifest.json"


def _embed_via_http(image_url: str, endpoint: str) -> list[float]:
    # Imported lazily so the stub path (the common one for tests/CI) does
    # not need httpx on PYTHONPATH.
    import httpx

    resp = httpx.post(endpoint, json={"image_url": image_url}, timeout=30.0)
    resp.raise_for_status()
    vec = resp.json()["embedding"]
    if not isinstance(vec, list) or len(vec) != catalog_seed.EMBEDDING_DIM:
        got = len(vec) if isinstance(vec, list) else type(vec)
        raise ValueError(f"/embed returned bad vector shape: got len={got!r}")
    return [float(v) for v in vec]


def _generate_synthetic(
    count: int, *, use_stub: bool, embed_endpoint: str
) -> Iterator[dict[str, Any]]:
    """Yield synthetic-v1 rows via the source dispatch, embedding on demand."""
    for row in catalog_seed.rows_for_source("synthetic-v1", count=count):
        if not use_stub:
            row["embedding"] = _embed_via_http(row["image_url"], embed_endpoint)
        yield row


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="Path to config/avsa.toml (default: %(default)s).",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=None,
        help="Override [catalog.seed_count]; default reads from --config.",
    )
    parser.add_argument(
        "--database-url",
        default=os.environ.get(
            "DATABASE_URL", "postgresql://avsa:avsa@localhost:5434/avsa"
        ),
        help="Postgres connection string (default: $DATABASE_URL or local).",
    )
    parser.add_argument(
        "--embed-url",
        default=os.environ.get("AVSA_EMBED_URL", DEFAULT_EMBED_URL),
        help="ViT /embed endpoint when not using the stub (synthetic-v1 only).",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Fashion200k manifest JSON (source=fashion200k); default: %(default)s.",
    )
    parser.add_argument(
        "--embedding-artifact",
        type=Path,
        default=None,
        help=(
            "Directory of the embedding artifact (embeddings.jsonl + "
            "manifest.json). Required when source=fashion200k."
        ),
    )
    return parser.parse_args()


def _build_storage_backend(config_path: Path) -> Any:
    """Construct the configured StorageBackend from config/avsa.toml.

    Reuses ``avsa_core.storage._build_backend`` so the backend selection and
    signed-url TTL bounds stay config-driven (never hardcoded here).
    """
    import tomllib

    from avsa_core.storage import _build_backend

    with config_path.open("rb") as fh:
        raw = tomllib.load(fh)
    return _build_backend(raw)


def _rows_for_seed(
    cfg: catalog_seed.SeedConfig,
    count: int,
    args: argparse.Namespace,
    *,
    use_stub: bool,
) -> tuple[Iterator[dict[str, Any]], bool]:
    """Return ``(rows, include_text_embedding)`` for the configured source.

    Fail-fast: source=fashion200k without ``--embedding-artifact`` (or with a
    missing manifest / artifact dir) raises ``ValueError`` so ``main`` can emit
    a clear stderr message and exit non-zero before opening the DB connection.
    """
    if cfg.source == "synthetic-v1":
        rows = _generate_synthetic(
            count, use_stub=use_stub, embed_endpoint=args.embed_url
        )
        return rows, False
    if cfg.source == "fashion200k":
        # Default the artifact location to [catalog] embedding_artifact (config)
        # when --embedding-artifact isn't passed, so `just seed-catalog` and
        # stack-up's seed-on-empty are turnkey.
        artifact = args.embedding_artifact or (
            Path(cfg.embedding_artifact) if cfg.embedding_artifact else None
        )
        if artifact is None:
            raise ValueError(
                "source='fashion200k' needs an embedding artifact: pass "
                "--embedding-artifact or set [catalog] embedding_artifact in config"
            )
        manifest_path: Path = args.manifest
        artifact_dir: Path = artifact
        if not manifest_path.is_file():
            raise ValueError(f"manifest not found: {manifest_path}")
        # artifact_dir is a STORAGE key resolved by the StorageBackend against
        # [storage.local] root_path — NOT a CWD-relative filesystem path. Do not
        # os-stat it here (that contradiction made fashion200k seeding fail both
        # ways). load_embedding_artifact raises a clear NotFound via the backend
        # if the artifact is absent.
        backend = _build_storage_backend(args.config)
        rows = catalog_seed.rows_for_source(
            "fashion200k",
            count=count,
            manifest_path=manifest_path,
            artifact_dir=artifact_dir,
            backend=backend,
        )
        return rows, True
    raise ValueError(
        f"unknown catalog source {cfg.source!r}; "
        "expected 'synthetic-v1' or 'fashion200k'"
    )


def main() -> int:
    args = _parse_args()
    cfg = catalog_seed.load_config(args.config)
    count = args.count if args.count is not None else cfg.seed_count
    use_stub = os.environ.get("AVSA_EMBED_STUB") == "1"

    try:
        rows, include_text_embedding = _rows_for_seed(
            cfg, count, args, use_stub=use_stub
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr, flush=True)
        return 2

    # Imported here so test_catalog_seed.py can import the module under
    # test without psycopg present in environments that don't need it
    # (the helpers don't require psycopg at import time).
    import psycopg

    print(
        f"==> seeding catalog.products with {count} rows from {cfg.source!r} "
        f"(stub={use_stub}, text_embedding={include_text_embedding})",
        flush=True,
    )
    started = time.perf_counter()
    with psycopg.connect(args.database_url) as conn:
        written = catalog_seed.copy_rows(
            conn,
            rows,
            include_text_embedding=include_text_embedding,
        )
        conn.commit()
    elapsed = time.perf_counter() - started
    print(f"==> wrote {written} rows in {elapsed:.1f}s", flush=True)
    return 0 if written >= count else 1


if __name__ == "__main__":
    raise SystemExit(main())
